name: Terraform

on:
  pull_request:
    branches:
      - main
      - feature/**
  push:
    branches:
      - main
      - feature/**

jobs:
  terraform:
    permissions:
      id-token: write 
      contents: read

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.8

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::133644693386:role/crystal-github-actions-role

      - name: Terraform Init
        working-directory: terraform/production/networking
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform/production/networking
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/production/networking
        run: terraform plan
